### ISSUE TITLE
就是想问一下，包在哪里

### ISSUE THREAD

**Issue by Creeper666** [DazeCake/Mirai-BDXwebsocket#15]
找了半天也没看见包在哪里，大佬能否推个release

**Comment by DazeCake** [comment]
很抱歉因为BDX的停更，本项目已经停止更新。但您仍可以在[这里](https://www.minebbs.com/threads/bdxwebsocket-qq-bdx.4632/#post-24070)找到最后一个支持版本的可执行文件进行下载。我们正在酝酿一种更加通用的加载方式，它将会不久后在公布，敬请期待！
